"""Add category and price to Product

Revision ID: 098694b3b24e
Revises: 
Create Date: 2025-12-15 15:37:24.422043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098694b3b24e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
